### ISSUE TITLE
Rendering of radar stations

### ISSUE THREAD

**Issue by pyrog** [OpenNauticalChart/renderer#2]
### Only some "radio circle" are rendered for radar or AIS  (missing text "AIS" or "Ra")
* [Cap Couronne](https://www.openstreetmap.org/node/249202380)<br/>(Radar is missing on [Seamap](https://maps.grade.de/?zoom=18&lat=43.32555&lon=5.05305&layers=B0FTTTTFFFFFFFFTT))<br/>![Cap Couronne lighthouse](https://user-images.githubusercontent.com/2158081/65247677-1ec96780-daf1-11e9-9a77-00027ff24e10.png)
* Nodes [2342437621](https://www.openstreetmap.org/node/2342437621), [2342583834](https://www.openstreetmap.org/node/2342583834)-[2342583836](https://www.openstreetmap.org/node/2342583836), [2342583839](https://www.openstreetmap.org/node/2342583839)-[2342583841](https://www.openstreetmap.org/node/2342583841)<br/>(AIS are missing on [Seamap](https://maps.grade.de/?zoom=18&lat=54.116&lon=4.01164&layers=B0FTTTTFFFFFFFFTT))
But nodes [2342583837](https://www.openstreetmap.org/node/2342583837)-[2342583838](https://www.openstreetmap.org/node/2342583838) with the same tags are rendered correctly!
* [Radartoren Maasvlakte II](https://www.openstreetmap.org/way/561795525)<br/>(Radar is missing on [Seamap](https://maps.grade.de/?zoom=18&lat=51.98348&lon=3.98488&layers=B0FTTTTFFFFFFFFTT))
* Nodes [1814352146](https://www.openstreetmap.org/node/1814352146), [1814352122](https://www.openstreetmap.org/node/1814352122), [1814352151](https://www.openstreetmap.org/node/1814352151), [1814352171](https://www.openstreetmap.org/node/1814352171), <br/>(Radars are missing on [Seamap](https://maps.grade.de/?zoom=18&lat=53.02492&lon=8.88163&layers=B0FTTTTFFFFFFFFTT))
- node [1818778002](https://www.openstreetmap.org/node/1818778002)
- node [1907445577](https://www.openstreetmap.org/node/1907445577)
- [Maasvlakte](https://www.openstreetmap.org/way/171988333)

### No "radio circle" are rendered for Racon transponders
- node [1181480850](https://www.openstreetmap.org/node/1181480850)
- node [5402049210](https://www.openstreetmap.org/node/5402049210)

### Nothing is rendered but tag  seamark:type=* is missing
- Eolienne Flottante Floatgen
- node [5602558351](https://www.openstreetmap.org/node/5602558351)

### Some objects had issue few hours before
Is it a cache issue ?
* [Wybelsum](https://www.openstreetmap.org/node/2795900281)<br/>(Radar was missing on [Seamap](https://maps.grade.de/?zoom=18&lat=53.336&lon=7.1081&layers=B0FFFFFFFFFFFFFTT))
* [Radarpost Hoofdplaat](https://www.openstreetmap.org/way/272003575)<br/>(Radar was missing on [Seamap](https://maps.grade.de/?zoom=18&lat=51.37029&lon=3.68632&layers=B0FTTTTFFFFFFFFTT))
* [Strömmen W](https://www.openstreetmap.org/node/4348605643) <br/>(AIS was missing on [seaMap](https://maps.grade.de/?zoom=18&lat=59.32178&lon=18.07893))  ?
- node [1195391665](https://www.openstreetmap.org/node/1195391665)
- node [4080726200](https://www.openstreetmap.org/node/4080726200)
- node [4080726201](https://www.openstreetmap.org/node/4080726201)
- node [5387924615](https://www.openstreetmap.org/node/5387924615)
- node [5402049208](https://www.openstreetmap.org/node/5402049208)
- node [5402049209](https://www.openstreetmap.org/node/5402049209)

**Comment by malcolmh** [comment]
I have found & fixed some bugs in the renderer which address these missing annotations and re-rendering is in progress.

Note that "Ra" is only displayed for "coast" radars and not for "surveillance" radars.

Objects without a "seamark:type" tag do not get rendered.

There does seem to be some delay in new renderings appearing in the maps.grade.de map. The opennauticalchart.org & map.openseamap.org maps do not delay.

**Comment by Dirk--** [comment]
maps.grade.de: Yes, I am using http://tilestache.org as a proxy provider serving seamark-tiles: Delay is likely!

**Comment by pyrog** [comment]
> I have found & fixed some bugs in the renderer which address these missing annotations and re-rendering is in progress.

Thank you very much 😄

> Note that "Ra" is only displayed for "coast" radars and not for "surveillance" radars.

Ok. Confirmed by _Radar, Radio - Satellite Navigation Systems_ section in [Symbols, Abbreviations and Terms used on paper Charts](https://www.iho.int/iho_pubs/standard/S-4/INT1_FR_Ed7_2019.pdf)

> Objects without a "seamark:type" tag do not get rendered.

Obvious. I will update them.

> There does seem to be some delay in new renderings appearing in the maps.grade.de map. The opennauticalchart.org & map.openseamap.org maps do not delay.

I didn't know [opennauticalchart.org](http://opennauticalchart.org) alias of [map.openseamap.org](http://map.openseamap.org). Thanks

I didn't noticed that [maps.grade.de](http://maps.grade.de) have a cache. Thanks
FYI, I use OpenSeaMap layer in JOSM too (and cleared it's local cache).

Racon is not (yet ?) rendered:
- node [1181480850](https://www.openstreetmap.org/node/1181480850)

Theses surveillance radars are rendered correctly now, thank again.
But I guess that they are radar reflectors or racon in reality, is it ?
* Nodes [1814352146](https://www.openstreetmap.org/node/1814352146), [1814352122](https://www.openstreetmap.org/node/1814352122), [1814352151](https://www.openstreetmap.org/node/1814352151), [1814352171](https://www.openstreetmap.org/node/1814352171)
![4 radars on 1 bridge](https://user-images.githubusercontent.com/2158081/65320270-c56d4100-dba1-11e9-8759-bcf5e75d9b73.jpeg)

**Comment by malcolmh** [comment]
The new rendering is underway, it may take several hours to complete.

The WSV charts for the Weser show those bridge piers as having surveillance radars. I agree that it does unlikely, but will need a survey or more public documentation before changing the map.

**Comment by pyrog** [comment]
> but will need a survey

I added notes on OSM Maps. Maybe somebody will check it… ?

**Comment by pyrog** [comment]
> Objects without a "seamark:type" tag do not get rendered.

There is a lot of them. See https://github.com/osm-fr/osmose-backend/issues/620

> Racon is not (yet ?) rendered:
> * node [1181480850](https://www.openstreetmap.org/node/1181480850)

Done, thanks 😄 
![racon](https://user-images.githubusercontent.com/2158081/65335810-68838200-dbc5-11e9-87c6-e321d7a7a743.jpeg)

**Comment by pyrog** [comment]
Hallo Malcolm,

> September, 20th 
> 
> The new rendering is underway, it may take several hours to complete.
> 
> The WSV charts for the Weser show those bridge piers as having surveillance radars. I agree that it does unlikely, but will need a survey or more public documentation before changing the map.
> 
It seem it a radar reflector. Could you confirm it ?
https://www.openstreetmap.org/note/1932904 <https://www.openstreetmap.org/note/1932904>

Best regards,

—
Yves
