### ISSUE TITLE
Spire not rendered correctly

### ISSUE THREAD

**Issue by pyrog** [OpenNauticalChart/renderer#3]
JOSM plugin render spire in church correctly according to the [wiki](https://wiki.openstreetmap.org/wiki/Tag%3Aseamark%3Alandmark%3Afunction%3Dchurch#Functions).
Unfortunately, the renderer display only a spire.

Example: [node 7090522177](https://www.openstreetmap.org/node/7090522177)

<img width="697" alt="Landmark Spire, function Church" src="https://user-images.githubusercontent.com/2158081/71547702-c33a3000-29a3-11ea-85a4-5441a70bc0bb.png">

**Comment by malcolmh** [comment]
Fixed

**Comment by pyrog** [comment]
thanks Malcolm 😄
