### ISSUE TITLE
Name of mooring buoy is not rendered

### ISSUE THREAD

**Issue by pyrog** [OpenNauticalChart/renderer#4]
Example: node 7098387485 ([OSM](https://www.openstreetmap.org/node/7098387485)) ([SeamMap](http://map.openseamap.org/?zoom=18&lat=16.16704&lon=-61.78899&layers=BFTFFFFFFFF0TFFFFFFFFF))

**Comment by malcolmh** [comment]
Fixed

**Comment by pyrog** [comment]
Vielen dank 😄
