### ISSUE TITLE
Foul ground obstruction not yet rendered

### ISSUE THREAD

**Issue by pyrog** [OpenNauticalChart/renderer#5]
Hi Malcolm,

This obstruction is not rendered:
- seamark:obstruction:category=foul_ground
- seamark:type=obstruction

It is rendered with a # on french map:
<img width="121" alt="foul ground" src="https://user-images.githubusercontent.com/2158081/71885678-22820800-313b-11ea-9596-f1848616fda0.png">

Example : node [7098267206](https://www.openstreetmap.org/node/7098267206)

BR,

PS:
* « PA » mean "position approchée" (approximate position)
* « PD » mean "position douteuse" (questionable position)

**Comment by malcolmh** [comment]
Done
